### PR TITLE
Replace slack library from nlopes/slack to slack-go/slack

### PR DESCRIPTION
**Pull request by osamingo**
The `nlopes/slack` has moved to `slack-go/slack`.
Therefore, I replaced the slack library.

More detail: https://github.com/nlopes/slack/blob/master/README.md

### CODE REVIEW

**Comment by osamingo** [comment]
@fgrosse Please review it if you are free.

**Comment by fgrosse** [comment]
Hey, first of all thanks for the pull request :+1: 

The change itself looks fine, I wonder though what this means for compatibility. I.e. does this mean we we need to release a version v2.0.0?

**Comment by fgrosse** [comment]
The only exported place where I currently see that a type from the old import is still used is in the adapter configuration (i.e. `Config.SendMsgParams`).

I suppose releasing a v2 is ok but would then also mean a change of the import path at the caller (i.e. `github.com/go-joe/slack-adapter/v2`). :thinking:

**Comment by osamingo** [comment]
@fgrosse Thanks for your comment 🙌

> The change itself looks fine, I wonder though what this means for compatibility.

We can respond quickly when the Slack API changes.
The `nlopes/slack` isn't maintained, but `slack-go/slack` is.

> I suppose releasing a v2 is ok but would then also mean a change of the import path at the caller.

I think we don't need to update the major version. Because these PR changes don't break compatibility.
I think updating a revision or minor version is sufficient, as it is a change due to the GitHub organization migration of the slack library being used.

**Comment by fgrosse** [comment]
Sorry for the late reply.

I want to explain my concern a bit more:

Somebody might have the following program:

```go
package main

import (
	"fmt"

	"github.com/go-joe/joe"
	"github.com/go-joe/slack-adapter"
	nlopesslack "github.com/nlopes/slack"
)

func main() {
	b := joe.New("example",
		slack.Adapter("xoxb-1452345…", slack.WithMessageParams(nlopesslack.PostMessageParameters{
			Username: "Test",
		})),
	)
}
```

I'm concerned that this change breaks compatibility in the SemVer sense since upgrading without any change will break compilation of this program.

Therefore we can only release this change as v2 of the API. I think that's not a big deal really and I'm not afraid to increase major versions but its important to keep this in mind.

The updated version of the code above would then look like this:

```go
package main

import (
	"fmt"

	"github.com/go-joe/joe"
	"github.com/go-joe/slack-adapter/v2"
	slack2 "github.com/slack-go/slack"
)

func main() {
	b := joe.New("example",
		slack.Adapter("xoxb-1452345…", slack.WithMessageParams(slack2.PostMessageParameters{
			Username: "Test",
		})),
	)
}
```

**Comment by osamingo** [comment]
No problem.
I'll give you that. The type of argument has changed from this update.

I also praise the bump up to `2.0.0`.
https://github.com/golang/go/wiki/Modules

**Comment by fgrosse** [comment]
Hey, sorry it took so long to get back to this topic.

I'm gonna merge now and tag the result as v2.0.0. It's the first time I upgrade a library to v2 via go Modules so let's see how this plays out in the real world :crossed_fingers:

**Pull request merged**
